# Generated by Django 2.1.1 on 2019-03-30 07:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name='文本内容'),
        ),
    ]
